//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daarasystem.Toubasoft.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Toubasoft.Service.ServiceSOSSoap")]
    public interface ServiceSOSSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément nom de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEleve", ReplyAction="*")]
        Daarasystem.Toubasoft.Service.AddEleveResponse AddEleve(Daarasystem.Toubasoft.Service.AddEleveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEleve", ReplyAction="*")]
        System.Threading.Tasks.Task<Daarasystem.Toubasoft.Service.AddEleveResponse> AddEleveAsync(Daarasystem.Toubasoft.Service.AddEleveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEleveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEleve", Namespace="http://tempuri.org/", Order=0)]
        public Daarasystem.Toubasoft.Service.AddEleveRequestBody Body;
        
        public AddEleveRequest() {
        }
        
        public AddEleveRequest(Daarasystem.Toubasoft.Service.AddEleveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddEleveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prenom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string addr;
        
        public AddEleveRequestBody() {
        }
        
        public AddEleveRequestBody(string nom, string prenom, string addr) {
            this.nom = nom;
            this.prenom = prenom;
            this.addr = addr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEleveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEleveResponse", Namespace="http://tempuri.org/", Order=0)]
        public Daarasystem.Toubasoft.Service.AddEleveResponseBody Body;
        
        public AddEleveResponse() {
        }
        
        public AddEleveResponse(Daarasystem.Toubasoft.Service.AddEleveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddEleveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddEleveResult;
        
        public AddEleveResponseBody() {
        }
        
        public AddEleveResponseBody(string AddEleveResult) {
            this.AddEleveResult = AddEleveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSOSSoapChannel : Daarasystem.Toubasoft.Service.ServiceSOSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSOSSoapClient : System.ServiceModel.ClientBase<Daarasystem.Toubasoft.Service.ServiceSOSSoap>, Daarasystem.Toubasoft.Service.ServiceSOSSoap {
        
        public ServiceSOSSoapClient() {
        }
        
        public ServiceSOSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSOSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSOSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSOSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Daarasystem.Toubasoft.Service.AddEleveResponse Daarasystem.Toubasoft.Service.ServiceSOSSoap.AddEleve(Daarasystem.Toubasoft.Service.AddEleveRequest request) {
            return base.Channel.AddEleve(request);
        }
        
        public string AddEleve(string nom, string prenom, string addr) {
            Daarasystem.Toubasoft.Service.AddEleveRequest inValue = new Daarasystem.Toubasoft.Service.AddEleveRequest();
            inValue.Body = new Daarasystem.Toubasoft.Service.AddEleveRequestBody();
            inValue.Body.nom = nom;
            inValue.Body.prenom = prenom;
            inValue.Body.addr = addr;
            Daarasystem.Toubasoft.Service.AddEleveResponse retVal = ((Daarasystem.Toubasoft.Service.ServiceSOSSoap)(this)).AddEleve(inValue);
            return retVal.Body.AddEleveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Daarasystem.Toubasoft.Service.AddEleveResponse> Daarasystem.Toubasoft.Service.ServiceSOSSoap.AddEleveAsync(Daarasystem.Toubasoft.Service.AddEleveRequest request) {
            return base.Channel.AddEleveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Daarasystem.Toubasoft.Service.AddEleveResponse> AddEleveAsync(string nom, string prenom, string addr) {
            Daarasystem.Toubasoft.Service.AddEleveRequest inValue = new Daarasystem.Toubasoft.Service.AddEleveRequest();
            inValue.Body = new Daarasystem.Toubasoft.Service.AddEleveRequestBody();
            inValue.Body.nom = nom;
            inValue.Body.prenom = prenom;
            inValue.Body.addr = addr;
            return ((Daarasystem.Toubasoft.Service.ServiceSOSSoap)(this)).AddEleveAsync(inValue);
        }
    }
}
